export interface Product {
  id: string ; title: string ; description: string ; price: number ; minQuantity: number ; category: 'wedding-cards' | 'visiting-cards' | 'photo-frames' | 'albums' ; images: string[] ; featured?: boolean ; bestseller?: boolean ; }

export const products: Product[] = [
  {
    id: 'wc-15-1',
    title: 'Wedding Card IMG_9055',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9055.webp'],
    featured: true,
    bestseller: true,
  },
  {
    id: 'wc-15-2',
    title: 'Wedding Card IMG_9056',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9056.webp'],
    featured: true,
  },
  {
    id: 'wc-15-3',
    title: 'Wedding Card IMG_9057',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9057.webp'],
    featured: true,
  },
  {
    id: 'wc-15-4',
    title: 'Wedding Card IMG_9059',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9059.webp'],
    featured: true,
  },
  {
    id: 'wc-15-5',
    title: 'Wedding Card IMG_9060',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9060.webp'],
    bestseller: true,
  },
  {
    id: 'wc-15-6',
    title: 'Wedding Card IMG_9061',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9061.webp'],
  },
  {
    id: 'wc-15-7',
    title: 'Wedding Card IMG_9062',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9062.webp'],
  },
  {
    id: 'wc-15-8',
    title: 'Wedding Card IMG_9063',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9063.webp'],
  },
  {
    id: 'wc-15-9',
    title: 'Wedding Card IMG_9064',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9064.webp'],
  },
  {
    id: 'wc-15-10',
    title: 'Wedding Card IMG_9065',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9065.webp'],
  },
  {
    id: 'wc-15-11',
    title: 'Wedding Card IMG_9067',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9067.webp'],
  },
  {
    id: 'wc-15-12',
    title: 'Wedding Card IMG_9068',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9068.webp'],
  },
  {
    id: 'wc-15-13',
    title: 'Wedding Card IMG_9069',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9069.webp'],
  },
  {
    id: 'wc-15-14',
    title: 'Wedding Card IMG_9070',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9070.webp'],
  },
  {
    id: 'wc-15-15',
    title: 'Wedding Card IMG_9071',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9071.webp'],
  },
  {
    id: 'wc-15-16',
    title: 'Wedding Card IMG_9072',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9072.webp'],
  },
  {
    id: 'wc-15-17',
    title: 'Wedding Card IMG_9073',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9073.webp'],
  },
  {
    id: 'wc-15-18',
    title: 'Wedding Card IMG_9074',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9074.webp'],
  },
  {
    id: 'wc-15-19',
    title: 'Wedding Card IMG_9075',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9075.webp'],
  },
  {
    id: 'wc-15-20',
    title: 'Wedding Card IMG_9077',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9077.webp'],
  },
  {
    id: 'wc-15-21',
    title: 'Wedding Card IMG_9078',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9078.webp'],
  },
  {
    id: 'wc-15-22',
    title: 'Wedding Card IMG_9079',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9079.webp'],
  },
  {
    id: 'wc-15-23',
    title: 'Wedding Card IMG_9080',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9080.webp'],
  },
  {
    id: 'wc-15-24',
    title: 'Wedding Card IMG_9082',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9082.webp'],
  },
  {
    id: 'wc-15-25',
    title: 'Wedding Card IMG_9083',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9083.webp'],
  },
  {
    id: 'wc-15-26',
    title: 'Wedding Card IMG_9084',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9084.webp'],
  },
  {
    id: 'wc-15-27',
    title: 'Wedding Card IMG_9085',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9085.webp'],
  },
  {
    id: 'wc-15-28',
    title: 'Wedding Card IMG_9086',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9086.webp'],
  },
  {
    id: 'wc-15-29',
    title: 'Wedding Card IMG_9087',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9087.webp'],
  },
  {
    id: 'wc-15-30',
    title: 'Wedding Card IMG_9088',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9088.webp'],
  },
  {
    id: 'wc-15-31',
    title: 'Wedding Card IMG_9089',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9089.webp'],
  },
  {
    id: 'wc-15-32',
    title: 'Wedding Card IMG_9090',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9090.webp'],
  },
  {
    id: 'wc-15-33',
    title: 'Wedding Card IMG_9091',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9091.webp'],
  },
  {
    id: 'wc-15-34',
    title: 'Wedding Card IMG_9092',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9092.webp'],
  },
  {
    id: 'wc-15-35',
    title: 'Wedding Card IMG_9093',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9093.webp'],
  },
  {
    id: 'wc-15-36',
    title: 'Wedding Card IMG_9094',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9094.webp'],
  },
  {
    id: 'wc-15-37',
    title: 'Wedding Card IMG_9095',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9095.webp'],
  },
  {
    id: 'wc-15-38',
    title: 'Wedding Card IMG_9096',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9096.webp'],
  },
  {
    id: 'wc-15-39',
    title: 'Wedding Card IMG_9097',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9097.webp'],
  },
  {
    id: 'wc-15-40',
    title: 'Wedding Card IMG_9098',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9098.webp'],
  },
  {
    id: 'wc-15-41',
    title: 'Wedding Card IMG_9099',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9099.webp'],
  },
  {
    id: 'wc-15-42',
    title: 'Wedding Card IMG_9100',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9100.webp'],
  },
  {
    id: 'wc-15-43',
    title: 'Wedding Card IMG_9101',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9101.webp'],
  },
  {
    id: 'wc-15-44',
    title: 'Wedding Card IMG_9102',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9102.webp'],
  },
  {
    id: 'wc-15-45',
    title: 'Wedding Card IMG_9104',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9104.webp'],
  },
  {
    id: 'wc-15-46',
    title: 'Wedding Card IMG_9105',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9105.webp'],
  },
  {
    id: 'wc-15-47',
    title: 'Wedding Card IMG_9106',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9106.webp'],
  },
  {
    id: 'wc-15-48',
    title: 'Wedding Card IMG_9107',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9107.webp'],
  },
  {
    id: 'wc-15-49',
    title: 'Wedding Card IMG_9108',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9108.webp'],
  },
  {
    id: 'wc-15-50',
    title: 'Wedding Card IMG_9109',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9109.webp'],
  },
  {
    id: 'wc-15-51',
    title: 'Wedding Card IMG_9110',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9110.webp'],
  },
  {
    id: 'wc-15-52',
    title: 'Wedding Card IMG_9112',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9112.webp'],
  },
  {
    id: 'wc-15-53',
    title: 'Wedding Card IMG_9113',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9113.webp'],
  },
  {
    id: 'wc-15-54',
    title: 'Wedding Card IMG_9114',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9114.webp'],
  },
  {
    id: 'wc-15-55',
    title: 'Wedding Card IMG_9115',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9115.webp'],
  },
  {
    id: 'wc-15-56',
    title: 'Wedding Card IMG_9116',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9116.webp'],
  },
  {
    id: 'wc-15-57',
    title: 'Wedding Card IMG_9117',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9117.webp'],
  },
  {
    id: 'wc-15-58',
    title: 'Wedding Card IMG_9118',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9118.webp'],
  },
  {
    id: 'wc-15-59',
    title: 'Wedding Card IMG_9121',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9121.webp'],
  },
  {
    id: 'wc-15-60',
    title: 'Wedding Card IMG_9122',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9122.webp'],
  },
  {
    id: 'wc-15-61',
    title: 'Wedding Card IMG_9123',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9123.webp'],
  },
  {
    id: 'wc-15-62',
    title: 'Wedding Card IMG_9124',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9124.webp'],
  },
  {
    id: 'wc-15-63',
    title: 'Wedding Card IMG_9125',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9125.webp'],
  },
  {
    id: 'wc-15-64',
    title: 'Wedding Card IMG_9126',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9126.webp'],
  },
  {
    id: 'wc-15-65',
    title: 'Wedding Card IMG_9127',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9127.webp'],
  },
  {
    id: 'wc-15-66',
    title: 'Wedding Card IMG_9129',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9129.webp'],
  },
  {
    id: 'wc-15-67',
    title: 'Wedding Card IMG_9130',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9130.webp'],
  },
  {
    id: 'wc-15-68',
    title: 'Wedding Card IMG_9131',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9131.webp'],
  },
  {
    id: 'wc-15-69',
    title: 'Wedding Card IMG_9132',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9132.webp'],
  },
  {
    id: 'wc-15-70',
    title: 'Wedding Card IMG_9133',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9133.webp'],
  },
  {
    id: 'wc-15-71',
    title: 'Wedding Card IMG_9134',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9134.webp'],
  },
  {
    id: 'wc-15-72',
    title: 'Wedding Card IMG_9135',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9135.webp'],
  },
  {
    id: 'wc-15-73',
    title: 'Wedding Card IMG_9136',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9136.webp'],
  },
  {
    id: 'wc-15-74',
    title: 'Wedding Card IMG_9137',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9137.webp'],
  },
  {
    id: 'wc-15-75',
    title: 'Wedding Card IMG_9138',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9138.webp'],
  },
  {
    id: 'wc-15-76',
    title: 'Wedding Card IMG_9139',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9139.webp'],
  },
  {
    id: 'wc-15-77',
    title: 'Wedding Card IMG_9140',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9140.webp'],
  },
  {
    id: 'wc-15-78',
    title: 'Wedding Card IMG_9141',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9141.webp'],
  },
  {
    id: 'wc-15-79',
    title: 'Wedding Card IMG_9142',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9142.webp'],
  },
  {
    id: 'wc-15-80',
    title: 'Wedding Card IMG_9143',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9143.webp'],
  },
  {
    id: 'wc-15-81',
    title: 'Wedding Card IMG_9144',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9144.webp'],
  },
  {
    id: 'wc-15-82',
    title: 'Wedding Card IMG_9145',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9145.webp'],
  },
  {
    id: 'wc-15-83',
    title: 'Wedding Card IMG_9146',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9146.webp'],
  },
  {
    id: 'wc-15-84',
    title: 'Wedding Card IMG_9147',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9147.webp'],
  },
  {
    id: 'wc-15-85',
    title: 'Wedding Card IMG_9148',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9148.webp'],
  },
  {
    id: 'wc-15-86',
    title: 'Wedding Card IMG_9149',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9149.webp'],
  },
  {
    id: 'wc-15-87',
    title: 'Wedding Card IMG_9150',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9150.webp'],
  },
  {
    id: 'wc-15-88',
    title: 'Wedding Card IMG_9151',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9151.webp'],
  },
  {
    id: 'wc-15-89',
    title: 'Wedding Card IMG_9152',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9152.webp'],
  },
  {
    id: 'wc-15-90',
    title: 'Wedding Card IMG_9153',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9153.webp'],
  },
  {
    id: 'wc-15-91',
    title: 'Wedding Card IMG_9154',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9154.webp'],
  },
  {
    id: 'wc-15-92',
    title: 'Wedding Card IMG_9155',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9155.webp'],
  },
  {
    id: 'wc-15-93',
    title: 'Wedding Card IMG_9156',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9156.webp'],
  },
  {
    id: 'wc-15-94',
    title: 'Wedding Card IMG_9157',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9157.webp'],
  },
  {
    id: 'wc-15-95',
    title: 'Wedding Card IMG_9158',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9158.webp'],
  },
  {
    id: 'wc-15-96',
    title: 'Wedding Card IMG_9159',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9159.webp'],
  },
  {
    id: 'wc-15-97',
    title: 'Wedding Card IMG_9160',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9160.webp'],
  },
  {
    id: 'wc-15-98',
    title: 'Wedding Card IMG_9161',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9161.webp'],
  },
  {
    id: 'wc-15-99',
    title: 'Wedding Card IMG_9162',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9162.webp'],
  },
  {
    id: 'wc-15-100',
    title: 'Wedding Card IMG_9163',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9163.webp'],
  },
  {
    id: 'wc-15-101',
    title: 'Wedding Card IMG_9164',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9164.webp'],
  },
  {
    id: 'wc-15-102',
    title: 'Wedding Card IMG_9165',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9165.webp'],
  },
  {
    id: 'wc-15-103',
    title: 'Wedding Card IMG_9166',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9166.webp'],
  },
  {
    id: 'wc-15-104',
    title: 'Wedding Card IMG_9167',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9167.webp'],
  },
  {
    id: 'wc-15-105',
    title: 'Wedding Card IMG_9170',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9170.webp'],
  },
  {
    id: 'wc-15-106',
    title: 'Wedding Card IMG_9171',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9171.webp'],
  },
  {
    id: 'wc-15-107',
    title: 'Wedding Card IMG_9172',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9172.webp'],
  },
  {
    id: 'wc-15-108',
    title: 'Wedding Card IMG_9173',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9173.webp'],
  },
  {
    id: 'wc-15-109',
    title: 'Wedding Card IMG_9174',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9174.webp'],
  },
  {
    id: 'wc-15-110',
    title: 'Wedding Card IMG_9175',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9175.webp'],
  },
  {
    id: 'wc-15-111',
    title: 'Wedding Card IMG_9176',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9176.webp'],
  },
  {
    id: 'wc-15-112',
    title: 'Wedding Card IMG_9178',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9178.webp'],
  },
  {
    id: 'wc-15-113',
    title: 'Wedding Card IMG_9179',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9179.webp'],
  },
  {
    id: 'wc-15-114',
    title: 'Wedding Card IMG_9180',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9180.webp'],
  },
  {
    id: 'wc-15-115',
    title: 'Wedding Card IMG_9181',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9181.webp'],
  },
  {
    id: 'wc-15-116',
    title: 'Wedding Card IMG_9182',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9182.webp'],
  },
  {
    id: 'wc-15-117',
    title: 'Wedding Card IMG_9183',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9183.webp'],
  },
  {
    id: 'wc-15-118',
    title: 'Wedding Card IMG_9184',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9184.webp'],
  },
  {
    id: 'wc-15-119',
    title: 'Wedding Card IMG_9185',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9185.webp'],
  },
  {
    id: 'wc-15-120',
    title: 'Wedding Card IMG_9186',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9186.webp'],
  },
  {
    id: 'wc-15-121',
    title: 'Wedding Card IMG_9187',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9187.webp'],
  },
  {
    id: 'wc-15-122',
    title: 'Wedding Card IMG_9188',
    description: 'Elegant wedding invitation card with beautiful design. Premium quality print on finest cardstock.',
    price: 15,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/15rs/IMG_9188.webp'],
  },
  {
    id: 'wc-25-1',
    title: 'Premium Wedding Card IMG_9312',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9312.webp'],
    featured: true,
    bestseller: true,
  },
  {
    id: 'wc-25-2',
    title: 'Premium Wedding Card IMG_9313',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9313.webp'],
    featured: true,
  },
  {
    id: 'wc-25-3',
    title: 'Premium Wedding Card IMG_9314',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9314.webp'],
  },
  {
    id: 'wc-25-4',
    title: 'Premium Wedding Card IMG_9316',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9316.webp'],
  },
  {
    id: 'wc-25-5',
    title: 'Premium Wedding Card IMG_9317',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9317.webp'],
  },
  {
    id: 'wc-25-6',
    title: 'Premium Wedding Card IMG_9318',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9318.webp'],
  },
  {
    id: 'wc-25-7',
    title: 'Premium Wedding Card IMG_9319',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9319.webp'],
  },
  {
    id: 'wc-25-8',
    title: 'Premium Wedding Card IMG_9320',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9320.webp'],
  },
  {
    id: 'wc-25-9',
    title: 'Premium Wedding Card IMG_9321',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9321.webp'],
  },
  {
    id: 'wc-25-10',
    title: 'Premium Wedding Card IMG_9322',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9322.webp'],
  },
  {
    id: 'wc-25-11',
    title: 'Premium Wedding Card IMG_9323',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9323.webp'],
  },
  {
    id: 'wc-25-12',
    title: 'Premium Wedding Card IMG_9324',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9324.webp'],
  },
  {
    id: 'wc-25-13',
    title: 'Premium Wedding Card IMG_9325',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9325.webp'],
  },
  {
    id: 'wc-25-14',
    title: 'Premium Wedding Card IMG_9326',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9326.webp'],
  },
  {
    id: 'wc-25-15',
    title: 'Premium Wedding Card IMG_9327',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9327.webp'],
  },
  {
    id: 'wc-25-16',
    title: 'Premium Wedding Card IMG_9328',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9328.webp'],
  },
  {
    id: 'wc-25-17',
    title: 'Premium Wedding Card IMG_9329',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9329.webp'],
  },
  {
    id: 'wc-25-18',
    title: 'Premium Wedding Card IMG_9330',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9330.webp'],
  },
  {
    id: 'wc-25-19',
    title: 'Premium Wedding Card IMG_9331',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9331.webp'],
  },
  {
    id: 'wc-25-20',
    title: 'Premium Wedding Card IMG_9332',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9332.webp'],
  },
  {
    id: 'wc-25-21',
    title: 'Premium Wedding Card IMG_9333',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9333.webp'],
  },
  {
    id: 'wc-25-22',
    title: 'Premium Wedding Card IMG_9334',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9334.webp'],
  },
  {
    id: 'wc-25-23',
    title: 'Premium Wedding Card IMG_9335',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9335.webp'],
  },
  {
    id: 'wc-25-24',
    title: 'Premium Wedding Card IMG_9336',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9336.webp'],
  },
  {
    id: 'wc-25-25',
    title: 'Premium Wedding Card IMG_9337',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9337.webp'],
  },
  {
    id: 'wc-25-26',
    title: 'Premium Wedding Card IMG_9338',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9338.webp'],
  },
  {
    id: 'wc-25-27',
    title: 'Premium Wedding Card IMG_9339',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9339.webp'],
  },
  {
    id: 'wc-25-28',
    title: 'Premium Wedding Card IMG_9340',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9340.webp'],
  },
  {
    id: 'wc-25-29',
    title: 'Premium Wedding Card IMG_9341',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9341.webp'],
  },
  {
    id: 'wc-25-30',
    title: 'Premium Wedding Card IMG_9342',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9342.webp'],
  },
  {
    id: 'wc-25-31',
    title: 'Premium Wedding Card IMG_9343',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9343.webp'],
  },
  {
    id: 'wc-25-32',
    title: 'Premium Wedding Card IMG_9344',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9344.webp'],
  },
  {
    id: 'wc-25-33',
    title: 'Premium Wedding Card IMG_9345',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9345.webp'],
  },
  {
    id: 'wc-25-34',
    title: 'Premium Wedding Card IMG_9347',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9347.webp'],
  },
  {
    id: 'wc-25-35',
    title: 'Premium Wedding Card IMG_9348',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9348.webp'],
  },
  {
    id: 'wc-25-36',
    title: 'Premium Wedding Card IMG_9349',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9349.webp'],
  },
  {
    id: 'wc-25-37',
    title: 'Premium Wedding Card IMG_9350',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9350.webp'],
  },
  {
    id: 'wc-25-38',
    title: 'Premium Wedding Card IMG_9351',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9351.webp'],
  },
  {
    id: 'wc-25-39',
    title: 'Premium Wedding Card IMG_9352',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9352.webp'],
  },
  {
    id: 'wc-25-40',
    title: 'Premium Wedding Card IMG_9353',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9353.webp'],
  },
  {
    id: 'wc-25-41',
    title: 'Premium Wedding Card IMG_9355',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9355.webp'],
  },
  {
    id: 'wc-25-42',
    title: 'Premium Wedding Card IMG_9357',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9357.webp'],
  },
  {
    id: 'wc-25-43',
    title: 'Premium Wedding Card IMG_9358',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9358.webp'],
  },
  {
    id: 'wc-25-44',
    title: 'Premium Wedding Card IMG_9364',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9364.webp'],
  },
  {
    id: 'wc-25-45',
    title: 'Premium Wedding Card IMG_9365',
    description: 'Premium wedding invitation card with exquisite design and superior finishing. Crafted on luxury cardstock.',
    price: 25,
    minQuantity: 50,
    category: 'wedding-cards',
    images: ['/products/25rs/IMG_9365.webp'],
  },
  {
    id: 'vc-001',
    title: 'Executive Gold',
    description: 'Premium visiting cards with gold foil embossing on luxury cardstock.',
    price: 15,
    minQuantity: 100,
    category: 'visiting-cards',
    images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800'],
    featured: true
  },
  {
    id: 'vc-002',
    title: 'Classic Professional',
    description: 'Clean and professional business cards with matte finish.',
    price: 8,
    minQuantity: 100,
    category: 'visiting-cards',
    images: ['https://images.unsplash.com/photo-1589041127168-9b1915731dc3?w=800']
  },
  {
    id: 'vc-003',
    title: 'Creative Studio',
    description: 'Artistic business cards with unique textures and creative designs.',
    price: 12,
    minQuantity: 100,
    category: 'visiting-cards',
    images: ['https://images.unsplash.com/photo-1572502742759-efb9c283a5db?w=800']
  },
  {
    id: 'pf-001',
    title: 'Ornate Gold Frame',
    description: 'Elegant photo frame with intricate gold detailing. Perfect for wedding photos.',
    price: 450,
    minQuantity: 1,
    category: 'photo-frames',
    images: ['https://images.unsplash.com/photo-1582053433976-25c00369fc93?w=800'],
    featured: true
  },
  {
    id: 'pf-002',
    title: 'Vintage Wooden Frame',
    description: 'Rustic wooden photo frame with distressed finish.',
    price: 350,
    minQuantity: 1,
    category: 'photo-frames',
    images: ['https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=800']
  },
  {
    id: 'pf-003',
    title: 'Modern Acrylic Frame',
    description: 'Contemporary clear acrylic frame for a minimalist look.',
    price: 280,
    minQuantity: 1,
    category: 'photo-frames',
    images: ['https://images.unsplash.com/photo-1581404917879-53e19259fdda?w=800']
  },
  {
    id: 'al-001',
    title: 'Premium Wedding Album',
    description: 'Luxurious leather-bound wedding album with lay-flat pages. 50 pages included.',
    price: 2500,
    minQuantity: 1,
    category: 'albums',
    images: ['https://images.unsplash.com/photo-1519741497674-611481863552?w=800'],
    featured: true,
    bestseller: true
  },
  {
    id: 'al-002',
    title: 'Classic Photo Album',
    description: 'Traditional photo album with acid-free pages. 30 pages included.',
    price: 1200,
    minQuantity: 1,
    category: 'albums',
    images: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800']
  },
  {
    id: 'al-003',
    title: 'Mini Memory Book',
    description: 'Compact photo album perfect for engagement or pre-wedding shoots.',
    price: 800,
    minQuantity: 1,
    category: 'albums',
    images: ['https://images.unsplash.com/photo-1544078751-58fee2d8a03b?w=800']
  }
] ; export const categories = [
  { id: 'wedding-cards', name: 'Wedding Cards', description: 'Elegant invitations for your special day' },
  { id: 'visiting-cards', name: 'Visiting Cards', description: 'Professional business cards' },
  { id: 'photo-frames', name: 'Photo Frames', description: 'Beautiful frames for precious memories' },
  { id: 'albums', name: 'Albums', description: 'Premium photo albums' }
] ; export function getProductsByCategory(category: string): Product[] {
  return products.filter(p => p.category === category) ; }

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured) ; }

export function getBestsellers(): Product[] {
  return products.filter(p => p.bestseller) ; }

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id) ; }
